In [1]:
from ml_core.metrics import error_metric_in_history_models
from ml_core.metrics.error_metrics import rmse, mae, mre
from ml_core.neural_networks.base_class import NetworkTrainer, Network, RegressionNetwork, ClassificationNetwork
from ml_core.data_process import add_ones_column, get_dummies, normalize_data
from ml_core.neural_networks.perceptron import PerceptronLayer
import pandas as pd
from sklearn.model_selection import train_test_split
from ml_core.normalization import max_min_normalization


import numpy as np

In [2]:
df_regression = pd.read_csv('data/concrete.csv', header=None)
df_classification = pd.read_csv('data/vowel.csv', header=None)

# Regressão

## Preparando os Dados

In [3]:
arr = df_regression.to_numpy()

X = arr[:, :-1]
y = arr[:, -1]

In [4]:
X_trn, X_, y_trn, y_ = train_test_split(X, y, test_size=0.4, random_state=42)

X_tst, X_val, y_tst, y_val = train_test_split(X_, y_, test_size=0.5, random_state=42)

In [5]:
X_trn_norm = normalize_data(X_trn, max_min_normalization)
X_trn_norm_bias = add_ones_column(X_trn_norm)

X_tst_norm = normalize_data(X_tst, max_min_normalization)
X_tst_norm_bias = add_ones_column(X_tst_norm)


y_trn_norm, desnomalize_function_regression = max_min_normalization(y_trn, with_denomalized=True)
y_trn_norm = y_trn_norm.reshape([-1, 1])

## Primeira Rede de Regressão

In [14]:
from ml_core.neural_networks.activate_functions import Tanh, Sigmoid

mlp_regression = RegressionNetwork.first_model(
    n_layers=10,
    n_neurons=5,
    n_features=X.shape[1],
    momentum=0.75,
    layer_type=PerceptronLayer,
    activation_function=Tanh,
    bias=0.01
)

In [15]:
mlp_regression.layers

array([<ml_core.neural_networks.perceptron.PerceptronLayer object at 0x000001986948B2B0>,
      dtype=object)

## Criando o Trainer

In [16]:
forward_backward_trainer = NetworkTrainer(
    mlp_regression, with_history=True, ephocs=1000, batch_size=50, regularization=0.2
)

## Treinando Para Regressão

In [17]:
trained_regression_model_history = forward_backward_trainer.fit(X_trn_norm_bias, y_trn_norm)

------------------0------------------
[[ 0.00900358 -1.24937037  0.06506885 -0.36946903 -0.39742904 -0.04624248
   0.48329653 -1.11881637 -0.01823214]
 [-0.00799479  0.00238062 -0.72396579  0.33670888 -0.24678423 -0.59464025
   1.19718767 -0.91258644  1.93847764]
 [-0.00489763  0.34964223  0.23371395  0.02324903 -0.33695692 -0.21259992
  -0.75657355 -0.74750143 -0.07272783]
 [ 0.01945082  0.74292007  0.45969255  1.44526482  1.41374181 -0.23046751
  -1.1832708   0.06400972  0.39373377]
 [ 0.03308516 -0.12342242 -0.26644067  0.89275325 -0.93627605  0.64278361
  -0.75794545 -0.81471011  0.04256882]]

[[ 0.00928009  0.27311502 -0.11964815  0.22032075 -0.51888437]
 [ 0.01951035 -0.75276689 -0.16703007  0.60728812 -0.42850994]
 [ 0.01195036  0.12410084  1.19452629 -0.95371282  0.7145618 ]
 [-0.03678702  0.00604678 -0.3393153   0.47853308  0.48884322]
 [-0.00789019 -1.34084794  0.02870173 -0.09279894  0.14322609]]

[[ 0.01022599 -0.48464521 -0.30077156  0.10329943 -0.738549  ]
 [ 0.01959317  

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



## Vendo Convergencia

In [18]:
error_metric_in_history_models(X_tst_norm_bias, y_tst, trained_regression_model_history, rmse, denomalize_function=desnomalize_function_regression)

[28.904577418924408,
 25.195146462548045,
 22.766465026668968,
 20.89418224154567,
 17.99325682778353,
 29.321200143729982,
 25.096630115696957,
 22.292623350582115,
 19.95049331488656,
 23.87800013261656,
 17.933473645346805,
 19.40039358843511,
 19.51116543163478,
 18.957041717815006,
 19.09625569967766,
 18.4874538332883,
 17.32533525636974,
 17.281951536124225,
 17.780789754555627,
 17.73373259021789,
 17.357825587977995,
 17.321340038569268,
 17.55099401044666,
 17.315383357895637,
 19.474937331436468,
 18.86356791470096,
 17.654698319449356,
 17.43605884664569,
 24.617188758966325,
 19.209861292468524,
 18.764501579716217,
 17.283022003415912,
 20.28631767614618,
 17.343948579073075,
 17.563452409804537,
 17.349403941310115,
 18.36825756568913,
 19.053365702567433,
 17.290030539444647,
 17.74492113478068,
 18.704269396795457,
 17.954095429534203,
 18.076532060329694,
 18.223753505200175,
 19.217199182245203,
 17.413018512625918,
 17.459964381259063,
 18.411759832462195,
 23.03580

In [13]:
preds = trained_regression_model[-1].predict(X_norm_bias)

NameError: name 'trained_regression_model' is not defined

# Classificação

In [ ]:
arr = df_classification.to_numpy()

X = arr[:, :-1]
y = arr[:, -1]

X_trn, X_, y_trn, y_ = train_test_split(X, y, test_size=0.4, random_state=42)

X_tst, X_val, y_tst, y_val = train_test_split(X_, y_, test_size=0.5, random_state=42)

X_trn_norm = normalize_data(X_trn, max_min_normalization)
X_trn_norm_bias = add_ones_column(X_trn_norm)

X_tst_norm = normalize_data(X_tst, max_min_normalization)
X_tst_norm_bias = add_ones_column(X_tst_norm)


y_trn_norm, desnomalize_function_classification = max_min_normalization(y_trn, with_denomalized=True)
y_trn_norm = y_trn_norm.reshape([-1, 1])

In [ ]:
mlp_classification = ClassificationNetwork.first_model(
    n_layers=5,
    n_neurons=5,
    n_features=X.shape[1],
    momentum=0.75,
    n_class=11,
    layer_type=PerceptronLayer,
    activation_function=Tanh,
    bias=0.2
)

In [ ]:
mlp_classification.layers

In [ ]:
np.unique(y).shape

In [ ]:
forward_backward_trainer = NetworkTrainer(
    mlp_classification, with_history=False, ephocs=6
)

In [ ]:
trained_regression_model_history = forward_backward_trainer.fit(X_trn_norm_bias, y_trn_norm)

In [ ]:
mlp_classification.predict(X_trn_norm_bias)

In [ ]:
idx = np.arange(10)

In [ ]:
np.random.shuffle(idx)

In [ ]:
idx

In [ ]:
idx_matrix = np.random.choice(idx, [100, 50])

In [ ]:
idx_matrix[0]